#+TITLE: Org Property Link Insertion Utility
#+AUTHOR: Your Name
#+DATE: [2024-08-07 Wed]

* Org Property Link Insertion Utility

** Intention
The Org Property Link Insertion utility allows you to quickly insert predefined links stored in Org-mode property drawers. This is particularly useful for frequently used links that you don't want to type out each time or for maintaining a centralized collection of important links within your Org files.

** Operation
1. Define links in your Org files using property drawers:
   #+BEGIN_SRC org
   :PROPERTIES:
   :LINK: [[valve-st-disabled][=Valve Disabled=]]
   :END:
   #+END_SRC

2. Use the keybinding =C-c C-x l= in any Org file to bring up a list of all defined links.
3. Select a link from the list to insert it at the cursor position.

** Installation

This utility can be installed using the `use-package` macro, which works for both standard Emacs and Doom Emacs.

1. Clone the repository:
   #+BEGIN_SRC sh
   git clone git@github.com:dfnr2/little-emacs-utils.git
   #+END_SRC

2. Add the following configuration to your Emacs init file
   (usually =~/.emacs=, =~/.emacs.d/init.el=, or =~/.doom.d/config.el= for Doom Emacs):

   #+BEGIN_SRC emacs-lisp
   (use-package org-property-link-insertion
     :after org
     :load-path "path/to/little-emacs-utils/org-mode"
     :bind (:map org-mode-map
                 ("C-c C-x l" . org-insert-property-link)))
   #+END_SRC

3. Replace "path/to/little-emacs-utils" with the actual path where you cloned the repository.
4. Restart Emacs or evaluate the configuration.

*** Note for Doom Emacs users:
If you want Doom to manage this package, add the following to your =packages.el= file:

#+BEGIN_SRC emacs-lisp
(package! org-property-link-insertion
  :recipe (:host github :repo "dfnr2/little-emacs-utils" :files ("org-mode/*.el")))
#+END_SRC

You can change the key binding by modifying the =:bind= section in the use-package declaration.

** Usage
After installation, you can start defining links in your Org files using the :LINK: property as shown in the Operation section. Then, use =C-c C-x l= to insert these links quickly in any Org file.

** Contributing
If you have ideas for improvements to this utility, please feel free to contribute! You can submit pull requests or open issues with your suggestions.

** License
This utility is released under the MIT License. See the LICENSE file for more details.
