#+TITLE: Org Property Links
#+AUTHOR: David Fenyes
#+EMAIL: dfnum2@gmail.com

* Overview

Org Property Links is an Emacs package that provides convenient functions to
 insert and create links stored in Org property drawers. It's useful for
 defining and quickly inserting frequently used links to be displayed by name
 rather than section number.

* Features

- Insert links from existing =:LINK:= properties in the current buffer
- Create new =:LINK:= properties based on the current Org element
- Customizable sorting options for link insertion
- Flexible link target selection (NAME, target definition, CUSTOM_ID, or heading)
- Insert long-form links (link and description), rendered as a clickable
  description, short form links (link only), rendered as a section number,
  or verbose links with a customizable format.

* Installation

** Manual Installation

1. Download =org-property-links.el= to your local machine.
2. Add the following to your Emacs configuration file:

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/path/to/org-property-links-directory")
(require 'org-property-links)
#+END_SRC

** Using use-package

#+BEGIN_SRC emacs-lisp
(use-package org-property-links
  :after org
  :load-path "~/.config/doom/lisp"
  :bind (:map org-mode-map
              ("C-c C-x l l" . org-property-links-insert-long)
              ("C-c C-x l s" . org-property-links-insert-short)
              ("C-c C-x l v" . org-property-links-insert-verbose)
              ("C-c C-x t" . org-property-links-toggle-tracking)
              ("C-c C-x L" . org-property-links-create))
  :config
  (setq org-property-links-sort-mode "description")
  (setq org-property-links-field "LINK")
  (setq org-property-links-tracking-field "TRACKING")
  ;; Verbose format: %s = link target, %d = description
  (setq org-property-links-verbose-format "[[%s][%d]] (Sec. [[%s]])"))
#+END_SRC

* Usage

** Inserting Links

Use =C-c C-x l l= (recommended binding) or =M-x org-property-links-insert-long=
to insert a link with both link target and description: =[[link][description]]=.

Use =C-c C-x l s= (recommended binding) or =M-x org-property-links-insert-short=
to insert a link with only the target: =[[link]]=. This renders as a section number.

Use =C-c C-x l v= (recommended binding) or =M-x org-property-links-insert-verbose=
to insert a link using the customizable verbose format. The default format is
=[[link][description]] (Sec. [[link]])=, which shows both the description and
section number. Customize via =org-property-links-verbose-format=.

Links will be presented according to the =org-property-links-sort-mode= setting.

** Creating Links

Use =M-x org-property-links-create= to create a new LINK property for the
current Org element. The default field value for a LINK is =:LINK:=. The field
name can be redefined via =org-property-links-field=. This function will create
a property drawer if one doesn't exist and add a LINK property based on the
current heading or element.

* Customization

You can customize the following variables:

** org-property-links-sort-mode

Determines how links are sorted when inserting. Possible values are:

- ="description"=: Sort links by their description (default)
- ="link"=: Sort links by their target URL

This can be set globally or as a file-local variable:

#+BEGIN_SRC emacs-lisp
(setq org-insert-link-sort-mode "description")
#+END_SRC

Or as a file-local variable:

#+BEGIN_SRC org
,#+PROPERTY: org-insert-link-sort-mode "link"
#+END_SRC

** org-property-links-field

The name of the property used to store links. Default is ="LINK"=. You can change it globally:

#+BEGIN_SRC emacs-lisp
(setq org-property-links-field "MY_LINK")
#+END_SRC

** org-property-links-verbose-format

The format string for verbose link insertion. Use =%s= for link target and =%d=
for description. Default is ="[[%s][%d]] (Sec. [[%s]])"=.

Examples:

#+BEGIN_SRC emacs-lisp
;; Default: description link followed by section reference
(setq org-property-links-verbose-format "[[%s][%d]] (Sec. [[%s]])")

;; Description with parenthetical section reference
(setq org-property-links-verbose-format "%d (see Sec. [[%s]])")

;; Just description with link in parentheses
(setq org-property-links-verbose-format "%d ([[%s]])")
#+END_SRC

* How It Works

** Inserting Links (org-property-links-insert)

1. Scans the current buffer for properties matching =org-property-links-field=
2. Parses the found links
3. Sorts the links based on =org-property-links-sort-mode=
4. Presents a list of links for the user to choose from
5. Inserts the selected link at the cursor position

** Creating Links (org-property-links-create)

1. Examines the current Org element
2. Determines the link target in the following order of preference:
   a. #+NAME: property
   b. <<target-definition>> in the heading
   c. :CUSTOM_ID: property
   d. Full heading text
3. Creates a property drawer if one doesn't exist
4. Adds a new property with the link

* Contributing

Contributions to Org Property Links are welcome! Please feel free to submit pull
requests or create issues on the GitHub repository.

* License

This project is licensed under the GNU General Public License v3.0. See the
LICENSE file for details.
